name: mon context

on: fork

jobs:
    info:
        runs-on : ubuntu-latest
        steps:
            - name: env information if fork
              run: echo "Here's env informations"
                   echo "${{ toJson(github) }}"

    
